apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
        - name: node-demo
          image: amanjain119/node-demo
          ports:
            - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during the rolling update

---
apiVersion: v1
kind: Service
metadata:
  name: node-demo
  labels:
    app: node-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    app: node-demo
